### ISSUE TITLE
Feature Requests :)

### ISSUE THREAD

**Issue by Vastrix** [unsee-cc/webserver#1]
* An android App (for easy uploading)

The problem is [Dstrux](https://dstrux.com/)..
This site is pretty much perfect, except that it's **not open-source** which makes it kinda suspicious.. 
("it's not paranoia if they're really after you" ;)

But if you could "borrow" all their features and implement it here.. that'd be lovely :P

(The site asks for feedback so.. :)

**Comment by Umkus** [comment]
Lol, nice. Thanks for sharing. I see almost exact same functionality as on Unsee. Somebody did their homework :smile:
